---
version: '3'
services:

  web-mysql:
    image: mysql:5.7
    env_file: ./.env
    ports:
      - "3306:3306"

  web:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./booking:/app
    ports:
      - "80:8080"
    command: ./scripts/cmd-web.sh
    environment:
      MYSQL_HOST: web-mysql
    env_file: ./.env
    depends_on:
      - web-mysql

  web-js:
    build:
      dockerfile: Dockerfile.js
      context: .
    volumes:
      - ./booking/static/js/app/:/app
    env_file: ./.env
    ports:
      - "3000:3000"
