# Generated by Django 2.0.2 on 2018-03-26 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicians', '0002_auto_20180224_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='id',
        ),
        migrations.AddField(
            model_name='musician',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
