# Generated by Django 2.0.2 on 2018-03-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_auto_20180326_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='email',
        ),
    ]
