# Generated by Django 2.0.2 on 2018-03-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_remove_musician_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='hometown',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
