# Generated by Django 2.0.2 on 2018-04-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0005_musician_hometown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='slug',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
