# Generated by Django 2.0.2 on 2018-04-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0006_auto_20180401_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='bio_short',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
