# Generated by Django 2.0.2 on 2018-04-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0007_musician_bio_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
