# Generated by Django 2.0.2 on 2018-04-15 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0008_musician_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
    ]
