# Generated by Django 2.0.2 on 2018-04-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0009_auto_20180415_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='stage_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
