# Generated by Django 2.0.2 on 2018-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0010_auto_20180415_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='image_hero',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
