# Generated by Django 2.0.2 on 2018-07-13 15:37

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0016_auto_20180620_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='genres',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='African,Alternative,Ambient,Americana,Asian,Avant-Garde,Blues,Caribbean,Christian,Classical,Comedy,Country,Electronic,Folk,Hip Hop,Jazz,Latin,Metal,Pop,Punk,R&B,Rock,Spoken Word,World', to='musicians.GenreTag'),
        ),
    ]
