# Generated by Django 2.0.2 on 2018-07-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0017_auto_20180713_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
