# Generated by Django 2.0.2 on 2018-06-19 17:54

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0018_auto_20180619_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='genres',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='African,Alternative,Ambient,Americana,Asian,Avant-garde,Blues,Caribbean,Christian,Classical,Comedy,Country,Electronic,Folk,Hip Hop,Jazz,Latin,Metal,Pop,R&amp;B,Rock,Spoken Word,World', to='musicians.Genres'),
        ),
    ]
