# Generated by Django 2.0.2 on 2018-10-11 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0020_auto_20180717_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='image_hero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_image', to='musicians.MusicianImage'),
        ),
    ]
