# Generated by Django 2.0.2 on 2018-10-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0020_auto_20180717_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='account_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('group', 'Group')], max_length=16, null=True),
        ),
    ]
