# Generated by Django 2.0.2 on 2018-10-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0021_auto_20181011_2324'),
        ('musicians', '0021_musician_account_type'),
    ]

    operations = [
    ]
