# Generated by Django 2.0.2 on 2019-02-19 02:47

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0022_merge_20181018_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianimage',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='genres',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='Acoustic,African,Afro,Ambient,Americana,Asian,Avant-Garde,Blues,Caribbean,Christian,Classical,Comedy,Country,Desi,Electronic,Folk,Funk,Hip Hop,Indie,Instrumental,Jazz,K-pop,Latin,Metal,Pop,Punk,Rap,Reggae,Rock,R&B,Soul,Spoken Word,World', to='musicians.GenreTag'),
        ),
    ]
