# Generated by Django 2.0.2 on 2018-03-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BookingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number_office', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number_cell', models.CharField(blank=True, max_length=256, null=True)),
                ('facebook', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter', models.CharField(blank=True, max_length=256, null=True)),
                ('instagram', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('event_type', models.SmallIntegerField(choices=[(0, 'CLUB'), (1, 'FESTIVAL'), (2, 'MUSIC_SERIES'), (3, 'PUBLICATION'), (4, 'COFFEE_HOUSE'), (5, 'BROADCAST'), (6, 'MANAGEMENT'), (7, 'SONGWRITING'), (8, 'SPECIAL_EVENTS'), (9, 'CONFERENCE'), (10, 'RECORD LABEL'), (11, 'COMPILATION'), (12, 'INTERNET')], null=True)),
                ('compensated', models.BooleanField(default=False)),
                ('compensation_food_drink_tickets', models.BooleanField(default=False)),
                ('compensation_general_compensation', models.BooleanField(default=False)),
                ('compensation_max_flat_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('compensation_min_flat_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('compensation_percent_of_door', models.DecimalField(decimal_places=2, max_digits=2)),
                ('compensation_percent_of_merchandise_sales', models.DecimalField(decimal_places=2, max_digits=2)),
                ('review_by_datetime', models.DateTimeField()),
                ('entry_start_datetime', models.DateTimeField()),
                ('entry_end_datetime', models.DateTimeField()),
                ('event_start_datetime', models.DateTimeField()),
                ('event_end_datetime', models.DateTimeField()),
                ('min_entry_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_entry_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address_city', models.CharField(blank=True, max_length=256, null=True)),
                ('address_region_country', models.CharField(blank=True, max_length=256, null=True)),
                ('address_region', models.CharField(blank=True, max_length=256, null=True)),
                ('address_street', models.CharField(blank=True, max_length=256, null=True)),
                ('address_string', models.CharField(blank=True, max_length=256, null=True)),
                ('website', models.CharField(blank=True, max_length=256, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('facebook', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter', models.CharField(blank=True, max_length=256, null=True)),
                ('instagram', models.CharField(blank=True, max_length=256, null=True)),
                ('claimed', models.BooleanField(default=True)),
            ],
        ),
    ]
