# Generated by Django 2.0.2 on 2018-03-06 21:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bookingagent',
            name='phone_number_cell',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bookingagent',
            name='phone_number_office',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=256, null=True),
        ),
    ]
