# Generated by Django 2.0.2 on 2018-09-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20180919_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_entry_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_entry_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
