# Generated by Django 2.0.2 on 2018-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
