# Generated by Django 2.0.2 on 2018-03-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_auto_20180310_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingagent',
            name='venues',
            field=models.ManyToManyField(to='venues.Venue'),
        ),
    ]
