# Generated by Django 2.0.2 on 2018-09-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_auto_20180919_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
