# Generated by Django 2.0.2 on 2018-10-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_venue_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
