# Generated by Django 2.0.2 on 2018-10-05 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_auto_20181005_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venues.Event'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='musician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicians.Musician'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
