# Generated by Django 2.0.2 on 2018-10-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_auto_20181005_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='compensated',
        ),
        migrations.RemoveField(
            model_name='event',
            name='compensation_food_drink_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='compensation_general_compensation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='compensation_max_flat_rate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='compensation_min_flat_rate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='compensation_percent_of_door',
        ),
        migrations.RemoveField(
            model_name='event',
            name='compensation_percent_of_merchandise_sales',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_entry_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='min_entry_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='review_by_datetime',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='slot',
            name='compensated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='compensation_food_drink_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='compensation_general_compensation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='compensation_max_flat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='compensation_min_flat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='compensation_percent_of_door',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='compensation_percent_of_merchandise_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='end_datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='start_datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
