# Generated by Django 2.0.2 on 2018-10-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_auto_20181005_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='notes',
            new_name='private_notes',
        ),
        migrations.AddField(
            model_name='slot',
            name='public_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
